apiVersion: wasme.io/v1
kind: FilterDeployment
metadata:
  name: fe-wasm-custom-filter
  namespace: default
spec:
  deployment:
    istio:
      kind: Deployment
      labels:
        app: myapp     
  filter:
    config: 'world'
    image: webassemblyhub.io/salrashid123/add-header:v0.1