apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: igpolicy
  namespace: istio-system
spec:
  targets:
  - name: istio-ingressgateway
    ports:
    - number: 80
    - number: 443
  origins:
  - jwt:
      issuer: "https://securetoken.google.com/firebase_PROJECTID"
      audiences:
      - "firebase_PROJECTID"
      jwksUri: "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"   
  principalBinding: USE_ORIGIN
---
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: svc1-policy
spec:
  targets:
  - name: svc1
  peers:
  - mtls: {}  
  origins:
  - jwt:
      issuer: "https://securetoken.google.com/firebase_PROJECTID"
      audiences:
      - "firebase_PROJECTID"
      jwksUri: "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"   
  principalBinding: USE_ORIGIN
---
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: svc2-policy
spec:
  targets:
  - name: svc2
  peers:
  - mtls: {}  
  origins:
  - jwt:
      issuer: "https://securetoken.google.com/firebase_PROJECTID"
      audiences:
      - "firebase_PROJECTID"
      jwksUri: "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"   
  principalBinding: USE_ORIGIN
